name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install . pyinstaller
      # Build ONCE with add-data (Windows uses backslash+semicolon)
      - run: pyinstaller --noconfirm --clean --name ward-core --dist build/dist --work build/work --add-data "ward_core\\config.yaml;." main.py
      # Verify config.yaml is bundled
      - run: powershell "Get-ChildItem -Path build/dist/ward-core | Select-Object Name"
      - run: powershell "Test-Path build/dist/ward-core/config.yaml"
      # Zip and checksum
      - run: powershell Compress-Archive -Path build/dist/ward-core/* -DestinationPath ward-core-${{ github.ref_name }}-windows-x64.zip
      - run: powershell "(Get-FileHash ward-core-${{ github.ref_name }}-windows-x64.zip -Algorithm SHA256).Hash | Out-File ward-core-${{ github.ref_name }}-windows-x64.zip.sha256"
      # Release
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ward-core-${{ github.ref_name }}-windows-x64.zip
            ward-core-${{ github.ref_name }}-windows-x64.zip.sha256

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install . pyinstaller
      # Linux/mac use forward slash+colon
      - run: pyinstaller --noconfirm --clean --name ward-core --dist build/dist --work build/work --add-data "ward_core/config.yaml:." main.py
      - run: ls -la build/dist/ward-core
      - run: test -f build/dist/ward-core/config.yaml
      - run: (cd build/dist && zip -r ../../ward-core-${{ github.ref_name }}-linux-x64.zip ward-core)
      - run: sha256sum ward-core-${{ github.ref_name }}-linux-x64.zip > ward-core-${{ github.ref_name }}-linux-x64.zip.sha256
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ward-core-${{ github.ref_name }}-linux-x64.zip
            ward-core-${{ github.ref_name }}-linux-x64.zip.sha256

  build-macos-x64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install . pyinstaller
      - run: pyinstaller --noconfirm --clean --name ward-core --dist build/dist --work build/work --add-data "ward_core/config.yaml:." main.py
      - run: ls -la build/dist/ward-core
      - run: test -f build/dist/ward-core/config.yaml
      - run: (cd build/dist && zip -r ../../ward-core-${{ github.ref_name }}-macos-x64.zip ward-core)
      - run: shasum -a 256 ward-core-${{ github.ref_name }}-macos-x64.zip > ward-core-${{ github.ref_name }}-macos-x64.zip.sha256
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ward-core-${{ github.ref_name }}-macos-x64.zip
            ward-core-${{ github.ref_name }}-macos-x64.zip.sha256

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install . pyinstaller
      - run: pyinstaller --noconfirm --clean --name ward-core --dist build/dist --work build/work --add-data "ward_core/config.yaml:." main.py
      - run: ls -la build/dist/ward-core
      - run: test -f build/dist/ward-core/config.yaml
      - run: (cd build/dist && zip -r ../../ward-core-${{ github.ref_name }}-macos-arm64.zip ward-core)
      - run: shasum -a 256 ward-core-${{ github.ref_name }}-macos-arm64.zip > ward-core-${{ github.ref_name }}-macos-arm64.zip.sha256
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ward-core-${{ github.ref_name }}-macos-arm64.zip
            ward-core-${{ github.ref_name }}-macos-arm64.zip.sha256
