name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -e . pyinstaller
      - name: Smoke: version prints
        run: |
          python -m ward_core --version
          python main.py --version
      - name: Build with PyInstaller
        run: pyinstaller ward-core.spec
      - name: Test PyInstaller build
        run: test -f dist/ward-core/config.yaml
      - name: Test PyInstaller executable
        run: |
          cd dist/ward-core
          ./ward-core --version